// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytjxktkhkvacrbtglpyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0anhrdGtoa3ZhY3JidGdscHlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2NzM3MzcsImV4cCI6MjA1NjI0OTczN30.TKAHkdppk8PDvn9jHRe9caieqpiornV9X23aiOTFuhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);