
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytjxktkhkvacrbtglpyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0anhrdGtoa3ZhY3JidGdscHlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2NzM3MzcsImV4cCI6MjA1NjI0OTczN30.TKAHkdppk8PDvn9jHRe9caieqpiornV9X23aiOTFuhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a custom typings interface to include our new tables
interface CustomTablesInterface extends Database {
  public: {
    Tables: {
      // Include testimonials from the Database types directly
      testimonials: Database["public"]["Tables"]["testimonials"];
      
      // Include the rest of the tables from Database
      reviews: Database["public"]["Tables"]["reviews"];
      review_replies: Database["public"]["Tables"]["review_replies"];
      bookings: Database["public"]["Tables"]["bookings"];
      profiles: Database["public"]["Tables"]["profiles"];
      turfs: Database["public"]["Tables"]["turfs"];
    };
    Views: Database["public"]["Views"];
    Functions: Database["public"]["Functions"];
    Enums: Database["public"]["Enums"];
    CompositeTypes: Database["public"]["CompositeTypes"];
  };
}

export const supabase = createClient<CustomTablesInterface>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
